### ISSUE TITLE
[BUG] Not downloading twitter properly. Only part of the whole profile, not all pics and vids.

### ISSUE THREAD

**Issue by krystian2160** [AAndyProgram/SCrawler#210] opened 2024-10-03 17:02 UTC
**Describe the bug**
Follow-up for this:
https://github.com/AAndyProgram/SCrawler/issues/155
As up is closed.

**To Reproduce**
Just download any bigger twitter profile, like 1000 - 2000 posts. It will only do less than 1000 mainly.

**Expected behavior**
To download everything twitter profile has posted.

**Release information:**
I have the latest release.

As sriwajaya572 said, https://github.com/mikf/gallery-dl/issues/5860 + they added countdown into gallery-dl.
Jdownloader downloads whole twitter profile with the right timeout, eg 20.000 ms for every request.
Can SCrawler download properly from twitter too? ❤️

**Comment by AAndyProgram** [comment] 2024-10-06 04:14
Please don't open new issues. Just continue the existing ones. I have notifications for new comments, and I see new comments in closed issues too, so if something changes I reopen the issue. You can also reopen a closed issue.

Duplicate of #155

**Closed by AAndyProgram** 2024-10-06 04:14 UTC
Labels: duplicate, enhancement, question, Twitter
