### ISSUE TITLE
Add ability to disable warning notification for large number of tagged instagram photos [REQUEST]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#49] opened 2022-05-27 10:37 UTC
left the program running overnight to download several new instagram users, came back to find it had stopped at the first profile and hadn't yet downloaded anything due to a warning notification that the user has a large number of tagged photos "taking a long time" (I expected it to take a long time. that's was why I left it overnight). When I confirmed and let it continue, it stopped again at the next profile with the same warning, and the next, and the next...

Would very much like the option to disable this and any other notifications that prevent downloads until being acknowledged. alternatively perhaps have it automatically resume if not acknowledged for 2 minutes

**Comment by AAndyProgram** [comment] 2022-05-27 12:12
You know, you need to carefully read the message box messages and **button tooltips**.
This message contains **four** buttons: ```Wait```, ```Wait (disable current)```, ```Abort```, ```Wait (disable all)```.
1. ```Wait``` - Wait and ask again when the error is found.
2. ```Wait (disable current)``` - Wait and skip future prompts while downloading the current profile.
3. ```Abort``` - Abort operation
4. ```Wait (disable all)``` - Wait and skip future prompts while downloading the current session.

https://github.com/AAndyProgram/SCrawler/blob/60b459e217051c02f615cee69168a58388470159/SCrawler/API/Instagram/UserData.vb#L119-L122

What does it mean:
1. This message will be annoyingly displayed on every action.
2. This message will no longer be displayed again when the current profile is **currently** downloading.
3. Cancel downloading the current profile (obviously)
4. **This message will no longer be displayed again on any profile in the current download session.**

You should have just pressed the fourth button (```Wait (disable all)```).

> Would very much like the option to disable this and any other notifications that prevent downloads until being acknowledged.

I added this prompt because this is Instagram. [After 195 requests](https://github.com/AAndyProgram/SCrawler/wiki/Settings#instagram-limits), SCrawler slows down downloading of Instagram profiles to avoid 429 error and account ban. SCrawler only receives 12 tagged content per request. So, if the message says there are 1000 posts, that means 84 requests will be spent! Next, the user needs to make a decision: is it worth it or not.

I don't know if I will implement it or not. This message box protects the user from account ban and long wait times. If you see a low number in this message (like 200), it doesn't mean the next profile does not have 50'000 tagged stuffs. In this case, it will not be downloaded even overnight!

> alternatively perhaps have it automatically resume if not acknowledged for 2 minutes

Definitely not

**Comment by TGJ64** [comment] 2022-05-27 12:58
Hi, sorry but we are talking about different prompts, I grabbed a screenshot this time to clarify:

![image](https://user-images.githubusercontent.com/100350754/170701787-fa2c0ff2-2d5d-4fab-95e8-6be72e3f70ce.png)

It is possible I am misunderstanding the options, but my interpretation of these is

1: "Continue" continues downloading tagged posts for the user
2: "Disable and Cancel" disables tagged post downloads for the user and cancels the present profile download
3: "Cancel"  cancels the present profile download but leaves the tagged post option

The issue is that it usually takes a while before the program will even give this prompt (and I've found the prompt doesn't always pop up in front if I am doing something else at the time, and I can then only find it via task manager) so if I have 2 accounts with a couple hundred tagged posts each and I set it to run before I go to bed, it might give the error 20 minutes later, downloading nothing, when it could have finished in a few hours

I generally have a good idea of how many tagged photos to expect, though I agree I'd want the warning if I missed one with over 10,000. I don't want to bypass the slowing-down of the download rate, just want to be able to skip the warning or maybe be able to set an acceptable value closer to like, 2000 if I so desire.

**Comment by AAndyProgram** [comment] 2022-05-27 13:04
Okay, I will think about

**Comment by AAndyProgram** [comment] 2022-05-27 21:15
> Hi, sorry but we are talking about different prompts

It is. Sorry, you are right. 🙃 

>will even give this prompt

The prompt is only displayed when the number of tagged posts excess 200.

>and I can then only find it via task manager

What? Why? 😮 

----

So... You're right, but still this message box protects the user from account ban and long wait times.

I'll think about how to do it, but it won't be soon. I'm currently very tired at work and don't have time to develop new features. As long as I'm currently very busy and tired at work, and till there are no critical bugs, I will temporarily not publish new releases. Until July. This issue is not a bug. _This message box was added intentionally and was added in releases 3.0.0.2-3.0.0.4 (I don't remember very well)._

But, if you urgently need this fix, I can only suggest that you download the code and build the fix.

If you don't want to be prompted at all, you need to remove the following code:
https://github.com/AAndyProgram/SCrawler/blob/26dca2246ef093c1f027dc32b7e64abdd6314918/SCrawler/API/Instagram/UserData.vb#L265-L277

If you want to increase the number of posts to display the message box, you need to replace the following code:
https://github.com/AAndyProgram/SCrawler/blob/26dca2246ef093c1f027dc32b7e64abdd6314918/SCrawler/API/Instagram/UserData.vb#L265
\- with-
```VB
If TaggedCount > 2000 Then
```
\- where 2000 is the number you want

You can also change ```Post limit timer``` to a lower value (eg 10000)
![InstagramSettings](https://raw.githubusercontent.com/AAndyProgram/SCrawler/60b459e217051c02f615cee69168a58388470159/ProgramScreenshots/SettingsSiteInstagram.png)

----

**ATTENTION. Add these "fixes" at your own risk. If you do this, I don't guarantee that your account will not be banned.**

**Comment by AAndyProgram** [comment] 2022-06-02 22:59
Will be in the next version

**Comment by AAndyProgram** [comment] 2022-06-03 17:50
Added. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).

Read more here: https://github.com/AAndyProgram/SCrawler/wiki/Settings#instagram-tagged-posts-limit

**If you like SCrawler, please like the program on [this site](https://alternativeto.net/software/scrawler/about/): https://alternativeto.net/software/scrawler/about/.**

**Closed by AAndyProgram** 2022-06-03 17:50 UTC
Labels: enhancement, Instagram
