### ISSUE TITLE
[Instagram] Not downloading  stories 

### ISSUE THREAD

**Issue by Bloodjack01** [AAndyProgram/SCrawler#124] opened 2023-04-29 14:33 UTC
The program works for everything except the stories , the ones showed with a glowing circle around the user profile.
(https://help.instagram.com/1660923094227526)

Is there an issue with them? 

Those stories stay only for 24 hours, and the whole point or this app (for me at least) is to be able to download them automatically so I won't miss any.

**Comment by AAndyProgram** [comment] 2023-04-29 15:37
Duplicate of #17

**Closed by AAndyProgram** 2023-04-29 15:37 UTC
Labels: Instagram
