### ISSUE TITLE
Issue with Instagram stories

### ISSUE THREAD

**Issue by T-prog3** [AAndyProgram/SCrawler#72] opened 2022-09-21 22:41 UTC
**Describe the bug**
I have an issue with Instagram where Scrawler is downloading the stories highlights, but not the story feed.

**Release information (please complete the following information):**
 - Windows 10
 - x64
 - Version 2022.9.17.0

**Comment by AAndyProgram** [comment] 2022-09-21 22:49
What do you mean "stories highlights"? Aren't "stories highlights" and "story feed" the same thing?

**Comment by T-prog3** [comment] 2022-09-21 22:53
No they are different. Highlights are the sticky collections under some users profiles who is permanent until the user remove them. The Story feed are when you click on their profile picture to see their story feed and this content is only active 24 hours.

**Comment by AAndyProgram** [comment] 2022-09-22 01:32
Got it.
Sorry, this will not be implemented. You can track this request [here](https://github.com/AAndyProgram/SCrawler/issues/17#issuecomment-1051085199).
Duplicate of #17

**Closed by AAndyProgram** 2022-09-22 01:32 UTC
Labels: duplicate, enhancement, Instagram

**Comment by T-prog3** [comment] 2022-09-22 07:27
1. Sorry but it is not a duplicate and that thread is full of misinformation that creates confusion.

2. It have been stated in both the `README.md` and in the software itself that `SCrawler` download `Stories` and now you telling me that it wont be be implemented?

3. If that really is the case then you should change the advertising.

4. As of now, the thing this software call "stories" and what that thread called "Pinned stories" are infact called `Highlights`. It's a collection where users can add their archived posts to show them off like an album and add new content over time but most people don't use this feature.

The actual `Stories` on the other hand is the second, if not most used feature of Instagram and why i downloaded this software. 
Both Highlights and Stories have similarities that can make people think that they are the same because Highlights were built as an extention that is connected to a users private story archive, still a separated feature though.

You can see this relation in their url paths.
Leo Messis `Stories`:
https://www.instagram.com/stories/leomessi/2932555915278807671/

Leo Messis `Highlights`:
https://www.instagram.com/stories/highlights/18056801944028464/

**Comment by AAndyProgram** [comment] 2022-09-22 15:58
1. Excuse me? Misinformation? 😱 What? 👀 This thread (especially in the first messages) contains all the information about which Instagram blocks I add, which ones I don't, and for what reasons.
2. All pinned stories are fully downloadable. **SCrawler downloads all pinned (archived) stories (number 4 in this [pic](https://github.com/AAndyProgram/SCrawler/issues/17#issue-1149170843))**.
3. I don't do this. Scrawler's description is correct. It can download stories.
4. 😐 

In this thread, I said that I didn't see these stories in the site's response. If I don't see them in the site's response, I can't develop this. Number 5 of this [message](https://github.com/AAndyProgram/SCrawler/issues/17#issuecomment-1051085199).

>It's a collection where users can add their archived posts to show them off like an album and add new content over time but most people don't use this feature.

And who is misinforming people? **Not posts, but Stories!** https://help.instagram.com/1935507879999791/
