### ISSUE TITLE
Date not being added to file name

### ISSUE THREAD

**Issue by blazer590** [AAndyProgram/SCrawler#60] opened 2022-07-20 14:55 UTC
Having the same issue in latest version 2022.7.7.0 date not adding to file name
[Settings.zip](https://github.com/AAndyProgram/SCrawler/files/9150969/Settings.zip)

**Comment by AAndyProgram** [comment] 2022-07-20 17:06
Duplicate of #35

**Closed by AAndyProgram** 2022-07-20 17:06 UTC
Labels: duplicate
